# Generated by Django 2.0.6 on 2018-07-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0007_auto_20180719_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='voter',
        ),
        migrations.AddField(
            model_name='post',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.WebUser'),
        ),
    ]
