# Generated by Django 2.0.6 on 2018-07-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0008_auto_20180720_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='voter',
        ),
        migrations.AddField(
            model_name='voter',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='voter',
            name='post_voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.WebUser'),
        ),
    ]
