# Generated by Django 2.0.6 on 2018-07-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0009_auto_20180720_1029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('post', 'post_voter')},
        ),
    ]
