# Generated by Django 2.0.6 on 2018-07-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180720_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_votes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
